### PR TITLE
Change is to are

### PR DESCRIPTION
**Pull request by DomThePorcupine**
Sorry I'm usually not a grammar guy but just wanted to help, again my apologies.

### CODE REVIEW

**Comment by mariogrip** [comment]
Thanks :)

**Comment by DomThePorcupine** [comment]
I am on a fresh install of 14.04.03 I ran the setup script and it failed 
to properly download everything.
It said 'done setup repositories' then 'Updates manifest'
and gave this error:
_fatal: remote opo already exists with different attribute__s_
any ideas on what the problem is?
Thanks so much I'd really like to help out
-Dom

**Comment by mariogrip** [comment]
I'll take a look at it, but I'm not in front of an computer right now, so I have to take a look at it later. But thanks for reporting.

**Comment by rahulraimarine** [comment]
hey guys......i would love to help, but i am only tech enthusiast & would like to be a tester if you have a build to test. pls let me know

**Pull request merged**
